import React from 'react';
import './globals.css'
import fontsConfig from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function applyFontsClasses() {
  const fontClassNames = Object.values(fontsConfig).map((font) => font.className);
  return fontClassNames.join(' ');
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={applyFontsClasses()} style={{ margin: 0, fontWeight: '600' }}>
        {children}
      </body>
    </html>
  )
}
