import './globals.css'
import { Newsreader, Roboto } from 'next/font/google'

const nw = Newsreader({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nw.className} style={{margin:0 , fontWeight:'600'}}>{children}</body>
    </html>
  )
}
